<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Insight</name>
   <tag></tag>
   <elementGuidId>c609b150-58b7-460b-b1f7-ce8850697e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='dashboard']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.lpx-main-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>41f1802a-d663-44d9-8f85-72a468dc3752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lpx-main-title</value>
      <webElementGuid>90b86986-de1e-490b-b9ad-14ceb78d8605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insight</value>
      <webElementGuid>f6e20368-7332-4099-a658-dfae938b9b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;row mb-2x5 align-items-center&quot;]/div[@class=&quot;col d-flex align-items-baseline&quot;]/h1[@class=&quot;lpx-main-title&quot;]</value>
      <webElementGuid>0fba1a5e-e787-4ea1-904a-d24bad446d28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='dashboard']/div/div/h1</value>
      <webElementGuid>a858f6f8-9c5f-4a24-b1ae-f0c42647871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a8122145-1fcc-48c7-86d6-b8648946ad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Insight' or . = 'Insight')]</value>
      <webElementGuid>bae74bd7-2fa9-45fd-ae31-298f9394322b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
