<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel  Import</name>
   <tag></tag>
   <elementGuidId>9539d189-ef61-4c9a-aa76-f0f686c69b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='abp-modal-footer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abp-modal-footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ec00d34-f962-4202-9587-e66b57487bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abp-modal-footer</value>
      <webElementGuid>52e83335-a130-4de6-8fd8-82c610da6927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-footer</value>
      <webElementGuid>790bbbe6-6448-4976-8656-d51b3a97e844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel  Import </value>
      <webElementGuid>f60eab01-c58f-4a63-a5eb-920470e51094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abp-modal-footer&quot;)</value>
      <webElementGuid>3cf616af-1167-4a14-9c10-4ac6ba4ec43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='abp-modal-footer']</value>
      <webElementGuid>77ed1f89-b10b-474b-b4ac-0328c9349019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-modal-window/div/div/div[3]</value>
      <webElementGuid>4568e29a-1dd0-40bd-a8e9-f5b544ac6288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'abp-modal-footer' and (text() = ' Cancel  Import ' or . = ' Cancel  Import ')]</value>
      <webElementGuid>5697773e-9651-49cf-bf1f-1f3ffa554ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
