<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LoginInput.UserNameOrEmailAddress</name>
   <tag></tag>
   <elementGuidId>eee28cf7-2278-4bad-a86c-289b30e4d4fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoginInput_UserNameOrEmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fefa45e0-74e3-4cd2-b678-b81ec71c60a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>533d9771-71f5-4ff1-9cda-de1ddb3a6f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>267239d2-6bf1-449f-b837-f86e5bb0db5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@example.com</value>
      <webElementGuid>4c188dfd-db3c-402a-8623-fada5b3c4bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b01da14-fc7b-4474-ba68-af7db9042859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field User name or email address must be a string with a maximum length of 256.</value>
      <webElementGuid>1024b874-4634-4d4e-b3ac-f2a2af57f947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>2ee38c1c-c3e4-4fa1-aec8-f1e983cf758a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The User name or email address field is required.</value>
      <webElementGuid>43af662e-e49d-44cb-944e-28c79bc14e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginInput_UserNameOrEmailAddress</value>
      <webElementGuid>139ce7cb-a6f1-4655-83d2-ffb855eadc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>8baa664e-248d-4fd2-bacb-3c8fa05d56f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginInput.UserNameOrEmailAddress</value>
      <webElementGuid>4bd82e88-b847-4ab4-a5c5-8906c715ba5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginInput_UserNameOrEmailAddress&quot;)</value>
      <webElementGuid>e3cd0c98-4348-41b6-9a24-8ef0c3a263dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LoginInput_UserNameOrEmailAddress']</value>
      <webElementGuid>4f7cef74-19bd-4761-b12b-2d20d5b93314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ccf2a571-9462-47cc-8db8-be246f14307f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'name@example.com' and @id = 'LoginInput_UserNameOrEmailAddress' and @name = 'LoginInput.UserNameOrEmailAddress']</value>
      <webElementGuid>16f4777d-feba-48b4-a7cc-d1798c5bb300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
